### ISSUE TITLE
Why copy dependencies

### ISSUE THREAD

**Issue by timolins** [fusepilot/parcel-plugin-cep#3]
At the moment all dependencies get copied (or linked) into the `dist` folder. Parcel should take care of all the dependencies – so why bother?

I noticed this because I started using yarn workspaces, which installs all dependencies in the workspace root. This caused my build to fail.

It works great for me without `copyDependencies()`.

**Comment by fusepilot** [comment]
It’s for node.js runtime dependencies. Like fs-extra, glob, etc...

I’m not super happy with the way it currently works. Id like to use `yarn install —production` instead, but it messes up the project’s node_modules folder.

**Comment by fusepilot** [comment]
Also, you should be safe to set all you're non-node.js, bundled dependencies, like react, redux, etc...  as `devDependencies`. That should solve your particular issue. Let me know if there's a problem with that.

**Comment by vespakoen** [comment]
This can be closed
