### ISSUE TITLE
Let's work together!

### ISSUE THREAD

**Issue by vespakoen** [fusepilot/parcel-plugin-cep#5]
Hey Michael,

I am Koen Schmeets and developer for MtMograph.
I have been working full time the last years making extensions for After Effects and Premiere Pro, and like you I was frustrated with the (out of the box) developer experience so I worked on creating a bundler and packager for Adobe extensions. The latest state of that work is found here:
https://github.com/adobe-extension-tools

I have also been working with Parcel and wanted to create a plugin for it, and then (luckily) stumbled on your package.

I really like the work you have done, and think together we can make it even better!

For example, live .jsx reloading!

```js
import {readFileSync} from 'fs';
const Buffer = Buffer || cep_node.Buffer

const jsxBundle = readFileSync('./dist/index.jsx.js').toString()
console.log(jsxBundle.length)
evalExtendscript(jsxBundle)
```
Anyways, just curious if you are up for a collaboration and if so, let's talk about it on some chat platform?

My email is hello@koenschmeets.nl you can also find me on google hangouts.
Curious to hear your thoughts!

- Koen

**Comment by fusepilot** [comment]
Hey Koen,

I'd love to chat more about collaborating and what you have in mind! Are you on the Motion Design Artists slack? That seems to be where the most discussion around this stuff is happening. I'm also `@fusepilot` there, hit me up.

Thanks!
